# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/hirsute64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    #Below command will sync the local folder qemu to the /vagrant_folder folder on the virtual machine. 
    #Hence, any files added to the qemu folder on your host machine will be available in the /vagrant_folder folder on the virtual machine.
    config.vm.synced_folder "qemu", "/vagrant_folder"
    
    config.vm.provision "shell", path: "vagrant_setup.sh"

  end
  